### ISSUE TITLE
Code style and rework.

### ISSUE THREAD

**Issue by knightburton** [Samsung/iotjscode#20]
I've added a few options to the eslintrc file (#19 PR) which we should use in my opinion. These options are not carved in stone, e.g.: I've set the code line length to 120 character because I think the 80 character is a bit old "approach", but this is just a brave idea. Please help me to find the best options for our purpose.

After the PR is landed I would like to rework the modules based on the new style and also I would like to improve the code a bit with the power of the ES6 features to imrpove performance and code management (e.g: the data array handling in the session module).

State of the rework (include the latest eslint rules): 
- [x] chart (#38)
- [x] client-connection (#30)
- [x] client-multimap (#27)
- [x] client-parsesource (#26)
- [x] client-protocol (#29)
- [x] completer (#31)
- [x] logger (#21)
- [x] main (#39)
- [x] session (#33)
- [x] surface (#32)
- [x] util (#22)

**Comment by daeyeon** [comment]
:-) The debate about the style that we postponed for a long time has begun. Because IoT.js has the same issue, I would like to give you and everyone a little longer feedback.

**Strategy**

First of all, I think that there are two approaches to apply coding styles. I'd ask which one we should select.

1. Make a set of `full` configurations and apply them all at once. 
2. Make a set of `minimal` configurations and improve it progressively.

**Leverage**

Plus, there are already configurations including a well-defined rules and best practices. Leveraging one of them seems a good way time-wise. We can select a popular or reasonable configuration and modify it with our perferences. Then, which configuration is suitable for our project? Please see the following candidates in my mind:

***Popularity***

`eslint-config-defaults` includes a list of configs. (https://www.npmjs.com/package/eslint-config-defaults) They're defined as default sets of configurations because of their popularity among developers.

1. eslint recommended (https://eslint.org/docs/rules), It includes very essential rules.
2. config-airbnb (https://github.com/airbnb/javascript, https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb)
3. config-google (https://github.com/google/eslint-config-google)

***Node.js friendly for IoT.js***
1. nodejs (https://github.com/nodejs/node/blob/master/.eslintrc.yaml)

There seems no eslint-config module for node.js itself. We may need to rewrite its `.eslintrc.yaml` for our purpose. It may sound not right to use a nodejs style rule for iotjscode. However, I mentioned it because it's a candidate discussed for iot.js. I'd like to hear opinions about the possibility to use one style rule for both projects.

**Comment by knightburton** [comment]
I see now this is a sensitive topic :D

Well, firstly, I think the first strategy would be a good choice (Make a set of full configurations as much as possible and apply them all at once - one module per commit maybe). The progressive imrpoveing can be very annoing in case like this, imho.

Secondly, the airbnb configuration is very popular as far as I know and that is define rules for ES6 which is great for iotjscode (but not the best for iot.js as I read in the iot.js discussion so far). However, I would choose this airbnb option instead of the others because this has a full configuration not just essential and we do not have to add too much rules by hand. If the ES6 config is not good for iot.js then that project can use the legacy ES5 version until ready for the latest verison. In this way we can use the same config with proper support on both project.

**Comment by daeyeon** [comment]
@knightburton With the opinions gathered, we also were requested to make one rule to apply both iot.js and iotjscode projects. While trying to apply airbnb rule to iot.js, it turned out that the current codes of iot.js has too many violations against airbnb rules to manually fix. So, as a more realistic alternative, we decided to write our own eslint rules based on eslint-recommended and google's one.

Please take a look at https://github.com/hs0225/iotjs/commit/416fcf7ffcfdb49fffe8007cc43fff5f4134cf55#diff-e4403a877d80de653400d88d85e4801a Please check them upon your perspective and share your opinions or concerns. You can think that it's allowed to slightly customize the rules for each project. e.g) 'max-len'

In order to avoid duplicate works, it seems better to land #21 and #22 once checking lint errors using the new rule.

**Comment by knightburton** [comment]
@daeyeon I understand your decision and that is absolute fine for me. Also, I've checked the private repo, and I think that if we could change the max-len to 120 (as you mentioned) in this project that would be perfect along with the rules which you have made. The only thing that is strange to me a bit is that the single quote comma (however I think that is just a rote in my case, so it is not a real problem).

Finaly, I am agree with you about the PRs, I will rework those after the new rules are landed here, too.

Thank you for informing me.

**Comment by knightburton** [comment]
I close this issue, since the reworks are done.

**Comment by knightburton** [comment]
I close this issue, since the reworks are done.
