### ISSUE TITLE
Direct JerryScript debugger not working?

### ISSUE THREAD

**Issue by chandruxp** [Samsung/iotjscode#80]
I tried to use it directly with JerryScript. But it is not working. I don't see the files loaded as well as I was not able to send files using Source send. I had the jerryscript runtime switch --debugger-wait-source while sending files. 

Jerry version 1.0  (e860870)

It worked with iotjs directly though.

**Comment by knightburton** [comment]
Hi @chandruxp!
If you are using one of the latest browser (except chrome), than the demo page (github.io) may not working because that page is under ssl and we are using not secure websocket to communicate with the debug server. The browser will not allow you to connect to a not secure websocket from a secure page.
Otherwise, must work with the latest jerryscript. Do you have any error log in your  browser console?

**Comment by chandruxp** [comment]
Hi @knightburton, Thanks for your response.

I'm not using demo page. I cloned jerryscript latest version.

    ./build/bin/jerry --start-debug-server --debugger-wait-source --log-level 3

Then I launched iotjscode in another terminal. I got the page running at ```localhost:8080```

I then connected using "Connect to" button to localhost:5001 . At this point I get Connected from: 127.0.0.1 message from jerry.

I got following error messages in browser console as soon as connected.

```
util.js:29 Uncaught Error: Assertion failed.
    at Function.assert (util.js:29)
    at WebSocket.abort [as abortConnection] (client-connection.js:77)
    at Connection.onmessage (client-connection.js:192)
assert @ util.js:29
abort @ client-connection.js:77
onmessage @ client-connection.js:192
util.js:29 Uncaught Error: Assertion failed.
    at Function.assert (util.js:29)
    at WebSocket.abort [as abortConnection] (client-connection.js:77)
    at Connection.onmessage (client-connection.js:192)
assert @ util.js:29
abort @ client-connection.js:77
onmessage @ client-connection.js:192
util.js:29 Uncaught Error: Assertion failed.
    at Function.assert (util.js:29)
    at WebSocket.abort [as abortConnection] (client-connection.js:77)
    at Connection.onmessage (client-connection.js:192)
assert @ util.js:29
abort @ client-connection.js:77
onmessage @ client-connection.js:192
util.js:29 Uncaught Error: Assertion failed.
    at Function.assert (util.js:29)
    at WebSocket.abort [as abortConnection] (client-connection.js:77)
    at Connection.onmessage (client-connection.js:192)
assert @ util.js:29
abort @ client-connection.js:77
onmessage @ client-connection.js:192
```

I tried to send a sample js code. But Run button is not enabled. 

I tried the python/html jerry debugger with the same and that works.

**Comment by knightburton** [comment]
@chandruxp I cloned the latest jerry and iotjscode again and its worked for me perfectly, and based on your first comment: "It worked with iotjs directly though." that should not work if you are using the latest iotjscode because the jerry submodule is not updated in the iotjs master yet (will be within a few days).

Therefore, based on your browser console log, the iotjscoce does not get the initial configuration message from the jerry right after the connection because of your iotjscode is outdated.

**Comment by knightburton** [comment]
@chandruxp FYI, the debugger protocol has been updated in the iotjs, too. If you are using the latest iotjscode, everything has to work.

**Comment by chandruxp** [comment]
@knightburton sorry for late response. And yes, the master copy works on latest Jerry. Thanks for the awesome project.
